### ISSUE TITLE
Issue installing packages on a Mac

### ISSUE THREAD

**Issue by pr0j3c7t0dd** [michaellatman/mcp-get#21]
Hello,

I'm getting the following error when I try to install a package on a Mac.  Any thoughts?:

Restarting Claude desktop app...
Failed to restart Claude desktop app: Error: Command failed: killall "Claude" && open -a "Claude"
_LSOpenURLsWithCompletionHandler() failed for the application /Applications/Claude.app with error -600.

    at genericNodeError (node:internal/errors:983:15)
    at wrappedFn (node:internal/errors:537:14)
    at ChildProcess.exithandler (node:child_process:421:12)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1104:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'killall "Claude" && open -a "Claude"',
  stdout: '',
  stderr: '_LSOpenURLsWithCompletionHandler() failed for the application /Applications/Claude.app with error -600.\n'
}

Mac OS: 15.1.1 (24B91)

**Comment by michaellatman** [comment]
Hello, did you have Claude closed at the time? It probably still installed correctly for you, even though this error occurred. But if Claude is closed, it will fail to relaunch.

**Comment by pr0j3c7t0dd** [comment]
Just tried it and made sure claude was open, and it worked correctly. Maybe you can add a check in at some point.  Thanks again!

**Comment by michaellatman** [comment]
Fixed! Thanks!

**Comment by pr0j3c7t0dd** [comment]
Verified works! Thank you!
