### ISSUE TITLE
Feature request - removing a package from the menu

### ISSUE THREAD

**Issue by pr0j3c7t0dd** [michaellatman/mcp-get#22]
Hello,

When I install a package, it doesn't seem to give me a menu item to remove the package, just installing again.  Would be nice to know what packages are currently installed and then have an option to remove them.

Thanks again, this project is great!

**Comment by michaellatman** [comment]
![CleanShot 2024-12-04 at 13 17 50@2x](https://github.com/user-attachments/assets/294cecb1-0436-4be3-9e0b-6604378aca5a)

When using the list command it should offer to uninstall if you installed via mcp-get

**Comment by pr0j3c7t0dd** [comment]
I've installed the filesystem package using mcp-get.  I did get the server to work once I added the extra parameter for allowed directories, however, I'm still not seeing the uninstall/reinstall options when I select it.  This is what I see on mac termal:

<img width="649" alt="Screenshot 2024-12-05 at 10 42 32" src="https://github.com/user-attachments/assets/0c5b419c-6d05-4485-843b-5051c32b8690">

**Comment by michaellatman** [comment]
Yup. New bug it seems. Reopening
